name: PR check!

on:
  # Sequence of patterns matched against refs/heads
  push:
    branches:    
      - '*'         # Push events on master branch
      - '!master'         # Push events on master branch

constants:
  job-config: &job-config
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
  steps:
    yarn-install: &yarn-install
      - name: install dependencies
        run: |
          yarn install --frozen-lockfile 

    checkout-n-yarn-install: &checkout-n-yarn-install
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - *yarn-install

jobs:
  typecheck:
    name: Type check
    <<: *job-config
    steps:
      - *checkout-n-yarn-install
      - name: type check
        run: yarn run type-check-ci

  lint:
    name: Lint
    <<: *job-config
    steps:
      - *checkout-n-yarn-install
      - name: lint
        run: yarn run lint

